name: NoSprint
main: aiptu\nosprint\NoSprint
src-namespace-prefix: aiptu\nosprint
version: 1.3.0
api: [5.0.0]
author: AIPTU
permissions:
  nosprint.bypass:
    default: op 
    description: Allows users to bypass sprint.
