# Do not change this (Only for internal use)!
config-version: 1.2

# Message used when canceling a player's sprint.
# You can use color codes by using "ยง" or "&" before the color code.
message: "&cYou can't sprint in this world."

# World Restriction Settings
worlds:
  # The mode can be either "blacklist," "whitelist," or "none".
  # - "blacklist" mode will cancel player's sprint in the specified worlds (blacklisted) and allow sprinting in other worlds.
  # - "whitelist" mode will allow player's sprint only in the specified worlds (whitelisted) and cancel sprinting in other worlds.
  # - "none" mode will not apply any restriction, and sprinting will be allowed in all worlds.
  mode: "blacklist"

  # List of world folder names to be blacklisted or whitelisted (depending on the mode set above).
  # If "mode" is set to "blacklist" or "whitelist," add the world folder names accordingly.
  # If "mode" is set to "none," leave the "list" empty ([]) to allow sprinting in all worlds.
  list:
    - "world"  # Example: "world" world folder is blacklisted, and players can't sprint here.
    - "world_nether"  # Example: "world_nether" world folder is blacklisted, and players can't sprint here.

# You can add more worlds to the list as needed.
# Note: Make sure to use the correct world folder names as specified in your PocketMine-MP server configuration.
# To disable world-specific sprint restriction and allow sprinting in all worlds, set "mode" to "none" and leave the "list" empty ([]) or remove the "list" entirely.
