---
# Do not change this (Only for internal use)!
config-version: 1

# Message used when canceling a player's sprint
# Use "ยง" or "&" to color the message
message: "&cYou can't sprint in this world"

# List of world folder names to blacklist sprint.
# Set it to [] if you want to sprint in all worlds.
blacklisted-worlds:
  - "world"
...