---
# Do not change this (Only for internal use)!
config-version: 1

# Message used when canceling a player's sprint
# Use "ยง" or "&" to color the message
message: "&cYou can't sprint in this world"

worlds:
  # The mode can be either "blacklist" or "whitelist".
  # Blacklist mode will cancel player's sprint according to predefined world folder names and will not cancel player's sprint in all worlds.
  # Whitelist mode will only allow player's sprint according to predefined world folder names and will cancel player's sprint in all worlds.
  mode: "blacklist"
  # List of world folder names to blacklist/whitelist (depending on the mode set above).
  # Set it to [] if you want to allow sprint in all worlds.
  list:
    - "world"
...